### ISSUE TITLE
Parse Templates Error w/ Script Command

### ISSUE THREAD

**Issue by joehand** [miracle2k/flask-assets#83]
I am getting the following error when I try to build assets using the `--parse-templates` option. Im not really sure where to start debugging this...

```
Searching templates...
Traceback (most recent call last):
  File "/Users/joe/Sites/_projects/words/venv3/lib/python3.4/site-packages/jinja2/nodes.py", line 386, in as_const
    return f(self.left.as_const(eval_ctx), self.right.as_const(eval_ctx))
  File "/Users/joe/Sites/_projects/words/venv3/lib/python3.4/site-packages/jinja2/nodes.py", line 365, in as_const
    raise Impossible()
jinja2.nodes.Impossible

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/joe/Sites/_projects/words/venv3/lib/python3.4/site-packages/jinja2/nodes.py", line 386, in as_const
    return f(self.left.as_const(eval_ctx), self.right.as_const(eval_ctx))
  File "/Users/joe/Sites/_projects/words/venv3/lib/python3.4/site-packages/jinja2/nodes.py", line 388, in as_const
    raise Impossible()
jinja2.nodes.Impossible

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 110, in <module>
    manager.run()
  File "/Users/joe/Sites/_projects/words/venv3/lib/python3.4/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/Users/joe/Sites/_projects/words/venv3/lib/python3.4/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/Users/joe/Sites/_projects/words/venv3/lib/python3.4/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/Users/joe/Sites/_projects/words/venv3/lib/python3.4/site-packages/flask_assets.py", line 422, in run
    return impl.main(args)
  File "/Users/joe/Sites/_projects/words/venv3/lib/python3.4/site-packages/webassets/script.py", line 557, in main
    return self.run_with_argv(argv)
  File "/Users/joe/Sites/_projects/words/venv3/lib/python3.4/site-packages/webassets/script.py", line 549, in run_with_argv
    return self.run_with_ns(ns)
  File "/Users/joe/Sites/_projects/words/venv3/lib/python3.4/site-packages/webassets/script.py", line 531, in run_with_ns
    env = self._setup_assets_env(ns, log)
  File "/Users/joe/Sites/_projects/words/venv3/lib/python3.4/site-packages/flask_assets.py", line 364, in _setup_assets_env
    env.add(*[b for b in self.load_from_templates(env, ns.jinja_extension)
  File "/Users/joe/Sites/_projects/words/venv3/lib/python3.4/site-packages/flask_assets.py", line 391, in load_from_templates
    load_bundles()
  File "/Users/joe/Sites/_projects/words/venv3/lib/python3.4/site-packages/webassets/ext/jinja2.py", line 218, in load_bundles
    bundles.extend(self.with_file(filename, self._parse) or [])
  File "/Users/joe/Sites/_projects/words/venv3/lib/python3.4/site-packages/webassets/loaders.py", line 301, in with_file
    return then_run(filename, contents)
  File "/Users/joe/Sites/_projects/words/venv3/lib/python3.4/site-packages/webassets/ext/jinja2.py", line 246, in _parse
    _recurse_node(node)
  File "/Users/joe/Sites/_projects/words/venv3/lib/python3.4/site-packages/webassets/ext/jinja2.py", line 244, in _recurse_node
    _recurse_node(node)
  File "/Users/joe/Sites/_projects/words/venv3/lib/python3.4/site-packages/webassets/ext/jinja2.py", line 237, in _recurse_node
    *AssetsExtension.resolve_contents(files.as_const(), self.asset_env),
  File "/Users/joe/Sites/_projects/words/venv3/lib/python3.4/site-packages/jinja2/nodes.py", line 490, in as_const
    return [x.as_const(eval_ctx) for x in self.items]
  File "/Users/joe/Sites/_projects/words/venv3/lib/python3.4/site-packages/jinja2/nodes.py", line 490, in <listcomp>
    return [x.as_const(eval_ctx) for x in self.items]
  File "/Users/joe/Sites/_projects/words/venv3/lib/python3.4/site-packages/jinja2/nodes.py", line 388, in as_const
    raise Impossible()
jinja2.nodes.Impossible
```

**Comment by manuelbua** [comment]
I've the same problem: it works fine if `auto_build` is active, but any attempt at the command line fails with more or less the same exception, did you find a workaround?

```
Traceback (most recent call last):
  File "run.py", line 9, in <module>
    from webfu.console import manager, term
  File "webfu/console/__init__.py", line 16, in <module>
    app, webapp = webfu.run()
  File "webfu/boot.py", line 121, in run
    m.run(['--parse-templates', 'build'])
  File "/home/manuel/.virtualenvs/webapp/lib/python2.7/site-packages/flask_assets.py", line 422, in run
    return impl.main(args)
  File "/home/manuel/.virtualenvs/webapp/lib/python2.7/site-packages/webassets/script.py", line 557, in main
    return self.run_with_argv(argv)
  File "/home/manuel/.virtualenvs/webapp/lib/python2.7/site-packages/webassets/script.py", line 549, in run_with_argv
    return self.run_with_ns(ns)
  File "/home/manuel/.virtualenvs/webapp/lib/python2.7/site-packages/webassets/script.py", line 531, in run_with_ns
    env = self._setup_assets_env(ns, log)
  File "/home/manuel/.virtualenvs/webapp/lib/python2.7/site-packages/flask_assets.py", line 364, in _setup_assets_env
    env.add(*[b for b in self.load_from_templates(env, ns.jinja_extension)
  File "xyz/lib/assets.py", line 26, in load_from_templates
    return Jinja2Loader(env, template_dirs, [jinja2_env], jinja_ext=jinja_extension).\
  File "/home/manuel/.virtualenvs/webapp/lib/python2.7/site-packages/webassets/ext/jinja2.py", line 218, in load_bundles
    bundles.extend(self.with_file(filename, self._parse) or [])
  File "/home/manuel/.virtualenvs/webapp/lib/python2.7/site-packages/webassets/loaders.py", line 301, in with_file
    return then_run(filename, contents)
  File "/home/manuel/.virtualenvs/webapp/lib/python2.7/site-packages/webassets/ext/jinja2.py", line 246, in _parse
    _recurse_node(node)
  File "/home/manuel/.virtualenvs/webapp/lib/python2.7/site-packages/webassets/ext/jinja2.py", line 244, in _recurse_node
    _recurse_node(node)
  File "/home/manuel/.virtualenvs/webapp/lib/python2.7/site-packages/webassets/ext/jinja2.py", line 237, in _recurse_node
    *AssetsExtension.resolve_contents(files.as_const(), self.asset_env),
  File "/home/manuel/.virtualenvs/webapp/lib/python2.7/site-packages/jinja2/nodes.py", line 490, in as_const
    return [x.as_const(eval_ctx) for x in self.items]
  File "/home/manuel/.virtualenvs/webapp/lib/python2.7/site-packages/jinja2/nodes.py", line 561, in as_const
    obj = self.node.as_const(eval_ctx)
  File "/home/manuel/.virtualenvs/webapp/lib/python2.7/site-packages/jinja2/nodes.py", line 604, in as_const
    obj = self.node.as_const(eval_ctx)
  File "/home/manuel/.virtualenvs/webapp/lib/python2.7/site-packages/jinja2/nodes.py", line 365, in as_const
    raise Impossible()
jinja2.nodes.Impossible
```

**Comment by joehand** [comment]
@manuelbua not really any good workout I've found...

**Comment by manuelbua** [comment]
Thanks for getting back to me: yesterday i was working on trying to get a grip on what's happening and find out that it looks like non-hardcoded strings in the `{% assets ... %}` block won't work in the `Jinja2Loader`: see my [other issue report](https://github.com/miracle2k/webassets/issues/401) at the `webassets` github.

**Comment by joehand** [comment]
@manuelbua interesting, thanks. I'll try that out...

**Comment by miracle2k** [comment]
Closing along with the webassets ticket.
