### ISSUE TITLE
"clean" command fails

### ISSUE THREAD

**Issue by keathmilligan** [miracle2k/flask-assets#85]
The flask-script "clean" command fails with:

Cleaning generated assets...
Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    manager.run()
  File "C:\Python27\lib\site-packages\flask_script\__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "C:\Python27\lib\site-packages\flask_script\__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "C:\Python27\lib\site-packages\flask_script\commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "C:\Python27\lib\site-packages\flask_assets.py", line 422, in run
    return impl.main(args)
  File "C:\Python27\lib\site-packages\webassets\script.py", line 557, in main
    return self.run_with_argv(argv)
  File "C:\Python27\lib\site-packages\webassets\script.py", line 549, in run_with_argv
    return self.run_with_ns(ns)
  File "C:\Python27\lib\site-packages\webassets\script.py", line 539, in run_with_ns
    return cmd.invoke(ns.command, args)
  File "C:\Python27\lib\site-packages\webassets\script.py", line 373, in invoke
    return function(**args)
  File "C:\Python27\lib\site-packages\webassets\script.py", line 299, in __call__
    file_path = bundle.resolve_output(self.environment)
  File "C:\Python27\lib\site-packages\webassets\bundle.py", line 326, in resolve_output
    output = ctx.resolver.resolve_output_to_path(ctx, self.output, self)
  File "C:\Python27\lib\site-packages\flask_assets.py", line 201, in resolve_output_to_path
    directory, rel_path, endpoint = self.split_prefix(ctx, target)
  File "C:\Python27\lib\site-packages\flask_assets.py", line 152, in split_prefix
    app = ctx.environment._app
AttributeError: 'Environment' object has no attribute 'environment'

The build command works. The flask-script manager was initialized with:

manager.add_command("assets", ManageAssets(assets))

**Comment by svenstaro** [comment]
Getting this too. Seems to indeed be a problem of flask-assets.

**Comment by keathmilligan** [comment]
I found a simple work-around. In your flask-script file, instead of adding the command the normal way, use the following:
```python
# work-around bug in flask-assets
app.jinja_env.assets_environment.environment = app.jinja_env.assets_environment
manager.add_command("assets", ManageAssets(app.jinja_env.assets_environment))
```
I don't recall where I found this, but thanks to whoever.

**Comment by SandeR2012** [comment]
line 152 in file flask_assets.py ```app = ctx.environment._app```  should be ```app = ctx._app ```

**Comment by miracle2k** [comment]
Same as #78.
